'use client'
import { Box, useTheme } from '@mui/material'
import axios from 'axios'
import Head from 'next/head'
import { ReactNode, useEffect } from 'react'
import CustomTextField from 'src/components/text-field'
import LayoutNotApp from 'src/views/layouts/LayoutNotApp'

export default function Home() {
  // test gọi api lấy danh sách user
  const fetchApiUser = async () => {
    await axios
      .get('http://localhost:3001/api/users?limit=10&page=1&order=created%20asc')
      .then(res => {
        console.log(res.data)
      })
      .catch(err => {
        console.log(err)
      })
  }
  useEffect(() => {
    fetchApiUser()
  }, [])

  // tìm hiểu về useTheme
  const theme = useTheme()
  console.log('theme have: ', { theme })

  return (
    <>
      <Head>
        <title>Quốc</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>Hello world!</h1>
      <Box sx={{ margin: 6, width: '200px' }}>
        <CustomTextField id='outlined-multiline-flexible' label='Multiline' />
      </Box>
    </>
  )
}

Home.getLayout = (pages: ReactNode) => <LayoutNotApp>{pages}</LayoutNotApp>
